In [33]:
#Question 1
import numpy as np

Array = np.array([11,22,33,44,55,66])

List = Array.tolist()

print(List)

[11, 22, 33, 44, 55, 66]


In [34]:
#Question 2
import numpy as np

a = np.array([[0,1,2],[3,4,5],[6,7,8]])
print('The initial array is:\n',a)

d = a.diagonal()
print("The diagonal elements: \n",d)

result = sum(d)
print('The sum of the diagonal elements of the array is:',result)

The initial array is:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
The diagonal elements: 
 [0 4 8]
The sum of the diagonal elements of the array is: 12


In [35]:
#Question 3
import numpy as np

a = np.array([[1,0,4],[2,5,3]])

rows = len(a)
columns = len(a[0])
l = []
x = 2

for i in range(rows):    
    for j in range(columns):        
        value = a[i,j]
        if value>x: 
            l.append(value)
print('The initial array is :\n',a)
print('The value higher than x are:\n',l)
        

The initial array is :
 [[1 0 4]
 [2 5 3]]
The value higher than x are:
 [4, 5, 3]


In [26]:
#Question 4
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
C = A + B
print(C)

[[ 6  8]
 [10 12]]


In [41]:
#Question 5
import numpy as np

A = np.array([[2, 1], [5, 4]])

A1 = np.mean(A, axis=1)
output = A - A1

print('The original matrix is :\n',A)

print('Mean of the matrix is :\n',A1)

print('The result is :\n',output)

The original matrix is :
 [[2 1]
 [5 4]]
Mean of the matrix is :
 [1.5 4.5]
The result is :
 [[ 0.5 -3.5]
 [ 3.5 -0.5]]
